### ISSUE TITLE
Combined mesh vertices loose welds.

### ISSUE THREAD

**Issue by kitbashery** [kitbashery/Kitbashery#10]
Unity's built-in mesh combiner removes welded vertices meaning when a mesh gets sent to a DCC all triangles are separated.

This can be fixed in one of 3 ways:

-Create a custom mesh combiner that preserves welded vertices in MeshCombiner.cs

or

-Weld vertices after the flawed combine using probuilder (or custom weld method) in BuildModeUI.CombineSelection()

or

-In all live link plugins have the DCC weld vertices on import.

**Comment by ghost** [comment]
The blender live link should fix this, however it is still ideal to have this done inside Kitbashery.

**Comment by ghost** [comment]
The cause of this issue might not be Unity (or just Unity) but the OBJExport.cs script changing triangle winding order and breaking welds. A new mesh combiner that welds vertices can be found here:

https://github.com/kitbashery/Kitbashery-Improved-Mesh-Combiner
