### ISSUE TITLE
Improve UV packing

### ISSUE THREAD

**Issue by kitbashery** [kitbashery/Kitbashery#11]
UVs of combined meshes in build mode are currently packed in a grid atlas this works find up until about 250 combines where it drifts out of UV coordinate bounds.

The packed UVs also are not ideal and can leave a lot of empty space.

A better approach would be to use a bin packing algorithm or integrating xatlas.
You can find a Unity port here: [https://github.com/kitbashery/xatlas-for-Unity](url)

UV packing can be found in MeshCombine.cs

**Comment by ghost** [comment]
UV packing can now be found in UVPacker.cs in experimental branch version 1.0.7+ however the current implmentation is still in MeshCombine.cs major refactoring will need to be done to both mesh combine and uv packing algorithms. Expect frequent changes.

**Comment by ghost** [comment]
UV packing and mesh combiner has been overhauled and replaced with this sub project:

https://github.com/kitbashery/Kitbashery-Improved-Mesh-Combiner
